name: Terraform Deploy Stage

on:
  workflow_dispatch: {}

jobs:
  terraform-deploy:
    name: Terraform Apply and App Deployment
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
      ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
      ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
      ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: |
          cd terraform
          terraform init -backend-config="access_key=${{ secrets.AZURE_STORAGE_KEY }}"

      - name: Download tfplan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: terraform

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply tfplan

      - name: Install Azure CLI
        run: |
          sudo apt-get update && sudo apt-get install -y azure-cli

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group ${{ secrets.AZURE_RG_NAME }} --name ${{ secrets.AZURE_AKS_CLUSTER_NAME }}

      - name: Deploy Kubernetes Manifests
        run: |
          kubectl apply -f kubernetes-manifests/